version: '3.8'

services:
  # Spring Backend
  backend:
    build: .
    ports:
      - "8082:8082"
    environment:
      - TIMELINE_SERVICE_URL=http://
      - TIMELINE_SERVICE_SECURE_PASSWORD=${TIMELINE_SERVICE_SECURE_PASSWORD}
      - FILE_JWT_SECRET=${FILE_JWT_SECRET}
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/chats
      - KEYCLOAK_ADMIN_USERNAME=${KEYCLOAK_ADMIN_USERNAME}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
    depends_on:
      - db
    networks:
      - app-network
    restart: unless-stopped

  # PostgreSQL Database (если нужна БД)
  db:
    image: postgres:16
    environment:
      - POSTGRES_DB=chats
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123
    ports:
      - "5432:5432"
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge


#    docker-compose up --build